### PR TITLE
doc/deprecations: sort out old/intermingled parts into revised structure

### PR DESCRIPTION
**Pull request by bar-g**

### CODE REVIEW

**Comment by andychu** [comment]
Hm another way to organize this doc is around "Oil Basic" here:

https://www.oilshell.org/release/latest/doc/oil-help-topics.html

## Two Deprecations That Are Both Pretty Unlikely

- `parse_paren` --- `if ( )` and while `( )` no longer means subshell
- `parse_at`  --- `@()` no longer means extended glob in pure OSH; use `,()` instead.  (But this is legacy -- it's not allowed in `simple_word_eval`  !)

Oh I guess `simple_word_eval` means that extended globs are only allowed in patterns, not command lines!   So maybe this is fairly big, but not sure.  This just happened in November.

## MInor Breakage 

- `parse_raw_string` - `r'foo'` means `foo`, not  `rfoo`

## Minor Quoting Issues

- `parse_brace` means `cd '{'`
- `parse_at` means `'@quoted'` if that's what you mean
- `=word` would have to be `'=word'`, which is an unconditional change, because the `=` operator is unconditionally on. 
- Could be worth mentioning: `'var' 'const'` 'proc'   if you need those as command names  (for legacy reasons)

------------

Overall I'm pretty impressed with how little breakage there is!

And maybe "shell language deprecations" is the wrong title for this doc.  I think it's more like "Incompatibilities When Upgrading to Oil".  (as opposed to writing a **new** Oil script.)

**Comment by andychu** [comment]
I would say the only thing that's really "deprecated" is extended glob in command lines because I didn't implement it under `simple_word_eval`.    (Extended globs in `[[` and `case` are supported.)

So arguably almost nothing is deprecated, but there are a half a dozen or so minor incompatibilities.  The biggest one is `if ()` and `while ( )`, and even those are quite uncommon in real shell code.  There is almost no reason to ever write those.

**Comment by bar-g** [comment]
Sure, sounds all very well. I don't know any details to add obviously, can merely tell you later what I didn't understand, just've put in what I picked up to be worth to sort out. Just tried to give more meaning to the headings and add the soft/hard differentiation, to show even more that there isn't much breakage to be afraid of.

**Comment by andychu** [comment]
Yes well thanks for pointing this out.  The feedback is useful

I think just limiting this PR to the minor edits I suggested could be good, or we could just wait until a rewrite (no promises on when that will happen -- I think the comment above is a pretty good start.)

It is also highly related to https://github.com/oilshell/oil/wiki/Gradually-Upgrading-Shell-to-Oil

**Comment by andychu** [comment]
Another thing that crossed my mind: We should emphasize the benefits of upgrading!

1. Simple word evaluation / fixing quoting hell
2. Reliable error handling -- all the stuff in the error handling doc

The other 2 of "4 features that justify a new Unix shell" are:

3. static parsing for better error messages and tools
4. QSN -- reliable processing of untrusted data

Those two are always on, whereas the first two are on only with `oil:basic/upgrade`.

**Comment by andychu** [comment]
I put the "flip side" on the wiki: https://github.com/oilshell/oil/wiki/Why-Use-Oil%3F

It is hard to explain because there are many different audiences for shell.

Honestly I feel like  on the home page there should be a big question:

- Do you like shell compatibility?  Why upgrade?
  - After all the benefits --   list these minor upgrade incompatibilites
- Do you want a brand new shell?  Why use Oil?

I get a lot of feedback from both audiences!

**Comment by bar-g** [comment]
Yes, but I don't think listing and repeating all the related stuff everywhere helps. At some point you will need to add structure and mainly add, move to, or modify things in that tree (table of contents). List all the benefits in one place, but definitely not in the deprecations document.  Otherwise it quickly becomes like navigating blog spam. I don't think what you'd need, and want above, is doable by small external edits from another person.

> "shell language deprecations" is the wrong title for this doc. I think it's more like "Incompatibilities When Upgrading to Oil". (as opposed to writing a new Oil script.)

Though, that's like the definition for deprecations. If there are only very few, the page should just be really short or the short list even just made part of say a broader usage page.

**Comment by bar-g** [comment]
Oh, and I did't read your last comment before sending my last one.

**Comment by bar-g** [comment]
Ok, now I looked into your linked wiki page.

Personally, I find those bullet points much better to read than its blog post publication it refers to.
The blog post seems to differ or incomplete and missing the structure and formatting.

So I think that you should very perfectly publish such as basic documentation that uses bullet point lists to give basic overviews. They can be read by users of any interest. Just make sure to keep to these doc texts more focused on things and not any persons's perspectives. Those you may later address separately, with a structured doc already out and maintained.

Here is what that page made me think could be a useful structure to gather and present all features, while still allowing them to be graspable by different audiences and according to different interests:



```
# Oilshell's feature comparison

Oilshell compared with its legacy shells

  osh (POSIX and bash compatible mode)
     starts fewer processes
     ...

  oil:upgrade (feature enabled mode)
    supports native, typed expressions and real data structures* (not broken as in bash): const, var, setvar
    ... : proc
    cleaned up shell I/O idioms*: read --line, read --all, write)
    ensures reliable errexit (problems solved, enabled by defalt)
    provides error handling*: try ... case _status {...}
  
      * actually already active in osh mode (may only break in other shells without support)
  
  oil:all (clean slate and final migration target)
    only disables...
    only deprecates...
    


Oilshell compared with python
  
  oil
    has more powerful and simple loop constructs: for i, key, value in (dict) {...}


Oilshell compared with javascript

  oil
  
```

**Comment by bar-g** [comment]
The idea being to present a feature in the comparison that most related to similarity and feature improvement.

**Comment by bar-g** [comment]
I revised the example for you. Note that I think the indentation is important, so even plain text would be better for this type of doc than loosing the structure in a html stream.

**Comment by bar-g** [comment]
Note, I think headers like "five or six unlikely" do not create a helpful category structure, also major/minor breakage is rather in the eye of the beholder. Therefore the layout above as suggested.

**Review by andychu — COMMENTED** [review]
Oh looks like I never published these pending comments from yesterday

**Comment by andychu** [comment]
Also what is the purpose of this change?  "document structure" is not a good description

I would like to see the preview, but on a high level I think the structure is "OK" -- the real problem with this doc is that it is 2 years old and needs to be updated to reflect all the changes we've settled on since then

**Comment by andychu** [comment]
I just read over this doc on my iPad with fresh eyes ... It seems OK,  the only issues I see are:

1. "Right now" title should be "Upgrading to Oil" 
2. Minor Breakages could be at the top level, maybe called "Extra Quotes May Be Required" -- it should also document `cd \{`
3. Some missing info mentioned, like `parse_raw_string`

**Comment by andychu** [comment]
I agree that we need a concise overview of features.  That is a good start, and it is pretty similar to what I drafted here:

https://github.com/oilshell/oil/wiki/Why-Use-Oil%3F

I added your comment at the top.

The reason it's all in blog format is somewhat on purpose -- because the Oil language is NOT done yet!

The OSH language is largely done, but Oil is not.

In particular I'm running into issues around #636.

I think around the time we fix #636 then we can advertise it more.  Also I need someone to help on the C++ translation.

Actually are you in the EU?  If you can help find a C++ / Python / compiler  engineer, that would be one of the best ways to move things forward

https://github.com/oilshell/oil/wiki/Compiler-Engineer-Job

We have a 50K euro grant to pay somebody!

**Comment by bar-g** [comment]
I adapted the changes according to what I understood from your comments. But left out putting in things new to me which I don't really understand, e.g. no idea what that `cd` issue you mentioned is about.

Maybe see if it fits.

**Comment by bar-g** [comment]
Concerning a consice overview of features, there is the same problem that I don't know enough to write it out myself. Would it help you if I put my draft from above on a wiki page with a code block or into a plain-text file?

But skimming through the reference I asked myself, does it get generated from the code?

Because if yes, then you could maybe also generate some kind of "positional fields" to each feature, based on the definition/occurrence? of its code (osh/oil:upgrade/oil:all). Then, together with some annotations/comments to denote origins/comparision of a feature (python/javascript/...), at least part of such a sorted feature overview could maybe be generated from the short one-liner descriptions that appear in the help-doc together with their "positional fields".

**Comment by bar-g** [comment]
Just moved the plain-text feature overview to https://github.com/oilshell/oil/wiki/Why-Use-Oil%3F , to have an editable version.

**Comment by bar-g** [comment]
> I would say the only thing that's really "deprecated" is extended glob in command lines because I didn't implement it under simple_word_eval.

Then you have removed/disabled or broken support.

https://en.wikipedia.org/wiki/Deprecation
The subshell syntax with parens is deprecated.

See preview:
https://github.com/oilshell/oil/blob/918167e9316224683ad8782f752abc6fbd6045cc/doc/deprecations.md

**Comment by andychu** [comment]
I changed the title and rewrote this doc:

https://www.oilshell.org/preview/doc/upgrade-breakage.html

Let me know if this covers what you were thinking!  Thanks

**Comment by bar-g** [comment]
> Deprecated -> Extendend globs

I believe that's not correct. Aren't extendend globs replaced or substituted, thus the old syntax disabled/unsupported?

I think the subshells outside of conditionals are actually deprecated (discouraged).

Move both of those up to their better corresponding section?

> Gated by Options

This is a rather general thing, for the clarity of documentation, maybe try to avoid all slang in favor of precise languange, and it's appreciated to have a coherent line of thought.

Rather than "this means this and that", for example, something like "Now extended globs @() notation no longer works, but they are still available using ,() notation."

**Comment by bar-g** [comment]
Also move the new stuff from the summery to the proper section.

**Comment by andychu** [comment]
OK I think you want it to make a distinction between "deprecated" and "unsupported".

But I think extended globs are "deprecated", because they're supported in `bin/osh`!

It think this is mostly a debate of the meaning of words ... 

Likewise maybe "Gated by" is an American thing ... I don't think it's "slang", but it could be different in other countries.  I will think about some more straightforward words

Thanks for the feedback

**Comment by andychu** [comment]
Updated it, thanks:

https://www.oilshell.org/preview/doc/upgrade-breakage.html

https://github.com/oilshell/oil/commit/5da011e388907ce52e394f0db03295cf75dc864e

**Comment by bar-g** [comment]
> distinction between "deprecated" and "unsupported"

sure: https://en.wikipedia.org/wiki/Deprecation
Both seem wrong to me:

If you call things that work in osh (and other shells) "deprecated", even though they must work there for compatibility?
And if you call things not working with oil:upgrade and oil:all "deprecated", even thought they are disabled in oil?

Just let the doc list all things disabled and deprecated **after enabling** oil:upgrade and you're fine. Maybe only use "discouraged"?
(But don't introduce `$(( x + 1 )), (( i++ )), [[ $s =~ $pat ]], and ${s%%prefix}` deprecations/discouragements only in a (therefore wrong) "summary".)

> With oil:upgrade Options

Does not seem to correspond to the code. In oil:all group maybe? parse_equals->hay?

**Comment by bar-g** [comment]
if ( ) and while ( ) take expressions, not subshells
if ( ) and while ( ) take expressions, not subshell commands

**Comment by bar-g** [comment]
r'c:\Users\' is a raw string
r'c:\Users\' is a raw string, not string join

**Comment by andychu** [comment]
OK thanks, the heading changes are good.

https://www.oilshell.org/preview/doc/upgrade-breakage.html

I changed it to "Unsupported", since "deprecated" can imply the support will go away.   And extended globs will always be supported in `bin/osh`.

**Comment by bar-g** [comment]
> I changed it to "Unsupported"

allright, now a doc structure starts appearing


More headings:

Extended Globs in Word Evaluation
Extended Globs in Word Evaluation, obsolete mini language

Or maybe use parens for the reasons everywhere:
Extended Globs in Word Evaluation (obsolete mini language)

##More Quotes May Be Needed
##More strings to quote (avoid parsing/errors)

###new keywords
###'@foo' (parse_at)  or parse_at_all?
###'cd '{'' (parse_brace)
###command '=' and '=x' (parse_equals)
* as it's disallowed anyway, what about using `=` as pretty print command instead of `_`, or discard (readable)

Still think it would be better to add another second level header "Discouraged Syntax", and below that listing the things from the "summary", at least as long as you don't have a separate page. But then maybe just rename the page to upgrade-changes? Oil is really not requiring that much changes, thanks to ...you.

**Comment by bar-g** [comment]
Maybe:

Discouraged Syntax (linting notices)

**Comment by bar-g** [comment]
Oh, `=` actually does work as pretty printer, already. :-) Definitely mention that nice side effect and justification.

Another thing that was in the old version is the deprecation of (...) subshells outside of the "changed syntax" in conditionals in idiomatic oil.

That could fit nicely into the additional, second-level section "Discouraged Syntax (linting notices, clean code)". Then it's getting a really nice `upgrade-changes.html`.

**Comment by andychu** [comment]
Thanks for the feedback, I think it's OK now ... I don't want more headings.  We want to avoid drowning in details that will rarely happen :)

**Comment by bar-g** [comment]
It's not about more headings at all, though. It's merely about changing the headings to use the two levels in a meaningful way, so they directly describe their section's content and the table of content becomes useful.

**Comment by bar-g** [comment]
The ToC is the essence for the reader. Gold to grasp things, quick and succinct and to go in to read only where needed.

"More Quotes May Be Needed", "With oil:upgrade Options", "Unconditionally" don't tell much do the reader, so the reader must read details or just leaves it beeing (not a good doc).

**Pull request closed without merging**
