### PR TITLE
[fix] extra import of pprint in devtools/make_help.py can cause error

### PR DESCRIPTION
**Pull request by asokoloski**
The error is:
Traceback (most recent call last):
  File "devtools/make_help.py", line 706, in <module>
    main(sys.argv)
  File "devtools/make_help.py", line 577, in main
    d = pprint.pformat(topic_lookup)
UnboundLocalError: local variable 'pprint' referenced before assignment

### CODE REVIEW

**Comment by andychu** [comment]
Oops, sorry about this.  I was working in a branch and didn't realize I landed something broken.

**Comment by asokoloski** [comment]
No worries!  easy to fix :)

**Comment by andychu** [comment]
OK I pulled and got past this error.  But I broke something else too.  Looking ...

**Comment by asokoloski** [comment]
Yeah, I think that one might just be that the minimal build doesn't include the help index?  My guess is that adding `build/doc.sh·help-index-text` to `gen-help` in `build/dev.sh` will fix it.

**Comment by asokoloski** [comment]
@andychu I ran into the same error locally, because I hadn't built the docs.

**Comment by andychu** [comment]
I just pushed:

https://github.com/oilshell/oil/commit/00cb9cef327d4fb062dd3aba026c653a38fbb7c1

`build/dev.sh all` and `minimal` should work now ... let me know if you have more problems.

**Comment by andychu** [comment]
And `test/unit.sh all` should work.  I did a big overhaul of the doc toolchain which I should describe on Zulip!

**Comment by asokoloski** [comment]
@andychu hmm, now my build/dev.sh minimal returns this error:

```
Traceback (most recent call last):
  File "devtools/make_help.py", line 705, in <module>
    main(sys.argv)
  File "devtools/make_help.py", line 612, in main
    with open(path, 'w') as f:
IOError: [Errno 2] No such file or directory: '_devbuild/help/_overview'
```

**Comment by andychu** [comment]
Oops sorry.  Will fix.  needs a `mkdir -p`

**Comment by andychu** [comment]
Let me know if it works now:

https://github.com/oilshell/oil/commit/8e4f3f876b3a23a11e347b5da6df9052b163a56e

**Comment by asokoloski** [comment]
@andychu building is now fine, but a unit test fails.  I don't know if it's a new failure, I haven't run the tests in a while:

```
======================================================================
FAIL: testFileSystemAction (__main__.CompletionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "core/completion_test.py", line 139, in testFileSystemAction
    self.assertEqual(expected, sorted(a.Matches(comp)))
AssertionError: Lists differ: ['configure', 'core', 'cpp'] != ['charset_test', 'configure', ...

First differing element 0:
'configure'
'charset_test'

Second list contains 1 additional elements.
First extra element 3:
'cpp'

- ['configure', 'core', 'cpp']
+ ['charset_test', 'configure', 'core', 'cpp']
?  ++++++++++++++++
```

**Comment by asokoloski** [comment]
@andychu durr, never mind. It's finding my temporary directory.  Realized as soon as I clicked "comment" :)

**Comment by andychu** [comment]
Yeah sorry the tests are sensitive to that.  I try to put most stuff under `_tmp`, but I get lazy and that's happened to me too.

**Comment by asokoloski** [comment]
@andychu anyway, yeah, the unit tests pass as well as they ever have.  I've had a failure in the testSearchPath test since I started playing with Oil, which seems to be due /bin/env existing on my system (as a copy of /usr/bin/env).  But that's fine.

**Comment by asokoloski** [comment]
Thanks for the quick fixes!

**Pull request merged**
