### PR TITLE
Add title to docs

### LINKED ISSUE #505: doc toolchain enhancements ( <title> tag, etc.)
e.g. the manual and

https://www.oilshell.org/release/0.7.pre5/doc/eggex.html

Someone mentioned this on reddit too.

### PR DESCRIPTION
**Pull request by tekknolagi**
Fixes #505

### CODE REVIEW

**Comment by tekknolagi** [comment]
Related: I can't figure out how to build the docs locally (or build anything at all):

```
emacs-mbp% ./configure
./configure: Wrote _build/detected-config.sh and _build/detected-config.h
emacs-mbp% make
test -d _build/opy && \
	  build/actions.sh app-deps opy /Users/emacs/Documents/dev/oil:/Users/emacs/Documents/dev/oil/vendor bin.opy_
build/actions.sh: line 69: _devbuild/cpython-full/python: No such file or directory
test -d _build/oil && \
	  build/actions.sh app-deps oil /Users/emacs/Documents/dev/oil:/Users/emacs/Documents/dev/oil/vendor bin.oil
build/actions.sh: line 69: _devbuild/cpython-full/python: No such file or directory
test -d _build/hello && \
	  build/actions.sh app-deps hello /Users/emacs/Documents/dev/oil/build/testdata:/Users/emacs/Documents/dev/oil/vendor hello
build/actions.sh: line 69: _devbuild/cpython-full/python: No such file or directory
emacs-mbp%
```

**Comment by andychu** [comment]
Hm I thought this would make <title> appear in the body of the doc not the <head> ?  


There are some instructions here for building the code:

https://github.com/oilshell/oil/wiki/Contributing

Building the docs isn't really documented but that could be fixed.

**Comment by andychu** [comment]
Also I just updated these two docs:

https://github.com/oilshell/oil/blob/master/README.md

https://github.com/oilshell/oil/blob/master/doc/README.md

Let me know if it doesn't make sense or doesn't work!

**Comment by andychu** [comment]
Thanks for the PR, but I'm working on doing this another way.  I'm still maintaining these issue labels if you're looking for something to hack on:

https://github.com/oilshell/oil/labels/good%20first%20issue

**Comment by tekknolagi** [comment]
Neat, will take a look. Cheers.

**Pull request closed without merging**
