### PR TITLE
support running as -osh for use as login shell

### PR DESCRIPTION
**Pull request by icarroll**
This is a fix for issue #34

### CODE REVIEW

**Comment by andychu** [comment]
OK great, thanks for fixing this!

I saw your issue but I wasn't quite sure what is different about a login shell.  But I think this is a good start.

**Comment by andychu** [comment]
And BTW I mostly expected people to use it as an interpreter for shell scripts, and to start it from your login shell (e.g. bash).  For example, it will sometimes crash on invalid input right now.  

Please report those bugs if you encounter them.  Although they may be a bit harder to catch if it's a login shell?  If the login shell crashes do you lose the ssh connection?

The completion support is still nascent too.

**Comment by icarroll** [comment]
I ran into the login shell issue when I was trying to test OSH on a complex shell script that configures and runs a web application. The simplest way to test was to change the user's shell to OSH and try to start the application, so it's sort of a yak shaving thing. Now that I have a fix, I will try again and report any problems that I find.

I'll also try the ;s error to see what happens when a login shell crashes.

**Comment by andychu** [comment]
Thanks for testing this out.  Let me know if there are some debugging features that might help.

I've been thinking of those as "carrots" for trying OSH.

1. a better `set -x`, in particular it should show the exit codes, and `set -e` failures.  (This one is always annoying).  Also `set -x` should be properly concurrent and show PIDs perhaps.

2. Being able to dump the state of the shell on a crash.  It's quite easy to dump all variables on the stack, but bash doesn't support this.  You can also dump all the `set/shopt` settings, as well as the file descriptor state, and a few other things.

**Comment by icarroll** [comment]
The main thing that would be useful to me so far would be saying what file and line a specific error was encountered at. On a crash I get plenty of (too much) information about where in the python code the error happened, but almost none about the shell code that triggered it.

**Comment by andychu** [comment]
OK I opened issue #38 about that.

There is infrastructure for providing location information, but sometimes I just raise NotImplementedError and it's not caught.

**Pull request merged**
