### PR TITLE
Add typechecking to osh/cmd_exec.py

### PR DESCRIPTION
**Pull request by asokoloski**
I found at least one bug in the process -- fix to follow.

### CODE REVIEW

**Comment by asokoloski** [comment]
@andychu ok, that's enough for me for tonight, I think :)

**Comment by asokoloski** [comment]
@andychu sorry, I should clarify -- this MR is ready to go, I think.  I'll put the bugfix stuff into another MR.

**Comment by andychu** [comment]
OK cool, taking a look ...

**Comment by andychu** [comment]
Beautiful, thank you!  And thanks for separating out the stuff that requires rewrites, which makes it easier to review.

**Comment by asokoloski** [comment]
@andychu :D  you're welcome!

Heh, I was planning to go more granular with the commits (splitting out variable renaming, etc.) but I decided it was probably not worth the trouble, in the end.  Maybe next time I can plan things a bit better, but it's tough to tell in advance what you'll need to do to fix the errors.

**Pull request merged**
