### PR TITLE
Add spec test for command with -p flag

### PR DESCRIPTION
**Pull request by KingMob**
Test of `command -p` that ignores existing PATH in favor of a default system PATH

Currently, dash/bash/mksh/zsh pass, osh fails.

Adds tests for, but does not fix, #1795

### CODE REVIEW

**Comment by andychu** [comment]
This looks great!  Thanks

Please changes `oils_allowed_failures` to 3 at the top of the file, and then it can be merged

It's a little hard to find but on the failing `ovm-tarball` task it will eventually lead to:

http://travis-ci.oilshell.org/github-jobs/5979/

I just go to

http://travis-ci.oilshell.org/github-jobs/

and then I search for the PR number.  Then I click through to the failures and it shows them:

http://travis-ci.oilshell.org/github-jobs/5979/#job-ovm-tarball

"Results" - http://travis-ci.oilshell.org/github-jobs/5979/ovm-tarball.wwz/_tmp/spec/osh-py/index.html


and then

http://travis-ci.oilshell.org/github-jobs/5979/ovm-tarball.wwz/_tmp/spec/osh-py/builtins2.html - scroll down to see the 3 cases


So we have many tools that take a bit of getting used to, but I think they're pretty helpful

**Comment by KingMob** [comment]
> Please changes oils_allowed_failures to 3 at the top of the file, and then it can be merged

Will do.

> http://travis-ci.oilshell.org/github-jobs/5979/ovm-tarball.wwz/_tmp/spec/osh-py/builtins2.html - scroll down to see the 3 cases

Ahh, ok. I was confused, because if I click on the Github ovm-tarball check [Details link](https://github.com/oilshell/oil/actions/runs/7624600522/job/20767088728?pr=1808), it says the error's in a task called "publish-html", which has zero direct mention of the specs, so it seemed unrelated.

**Comment by andychu** [comment]
Also I forget if I sent this, I usually send it to people and it has some tips

https://github.com/oilshell/oil/wiki/Where-Contributors-Have-Problems

We definitely want more people to be involved in the code, so I appreciate the contributions!

**Comment by KingMob** [comment]
Thanks! I think I'm going to remain an enthusiastic watcher on the sidelines for now, though. 

I have my own projects, [Aleph](https://github.com/clj-commons/aleph) and [Manifold](https://github.com/clj-commons/manifold/), to maintain, a side business I'm vetting, a new job at MIT next week, and I'm trying to become a DM to revive my D&D group again, so... 😛 

Good luck, though!

**Comment by andychu** [comment]
Oh OK, well thank you for getting involved !  If you have time, definitely stop in later

I hope it will be appealing when the language is more polished and documented :)  It's getting there

(I've been a big fan of Clojure from afar, in a different life I would be using it regularly !)

**Pull request merged**
