### PR TITLE
initial add of tour of oil

### PR DESCRIPTION
**Pull request by happysalada**
I started on a tour of oil path.
It's a .sh file to be executable. I thought that way it could be embedded into learnXinY
I'm open about the format.
This is an initial PR, not everything is included for sure.
Feel free to nitpick on anything, I don't mind changing wording or format.
Hopefully this gets the discussion going.

References that should probably be included
https://www.oilshell.org/release/latest/doc/eggex.html
https://www.oilshell.org/release/latest/doc/idioms.html
https://www.oilshell.org/release/latest/doc/oil-help.html

missing topics
- read
- write
- test

Documents that can provide inspiration
https://learnxinyminutes.com/docs/tcsh/
https://learnxinyminutes.com/docs/bash/

fixes https://github.com/oilshell/oil/issues/934

Idea
- I quite like the `putting it together` part at the end of https://learnxinyminutes.com/docs/zfs/
I'm thinking of including a simple script like a git hook maybe? At the end to illustrate the concepts.

### CODE REVIEW

**Comment by andychu** [comment]
The content looks good so far!  But I think that it should be one of two things:

- in the learn X in Y format and go in THAT repo (might be early, but it should happen eventually)
- in the same format as everything in `doc/`, and in our repo

I understand the desire to make it executable, and that's kind of a hole in our system.  But I don't want to accumulate TODOs since the docs are already a big undertaking and far from done.

Although it does seem very similar to the stuff here:

https://github.com/oilshell/oil/tree/master/oil_lang/testdata

It's possible that we can put the same content there AND it will be automatically run in the continuous build.  However that testdata is not published anywhere, which would be something else to do.

**Comment by andychu** [comment]
I guess one possible option is to put it in `testdata/` for now, and iterate on the content (and probably fix some language bugs uncovered!)

The `_match('year')` thing is just unimplemented, and that's something that someone else brought up.  So it would be nice to fix that.

I think that will get us started.  And then at some point we can convert it to the `doc/` format so it will appear on the web.  (This could be a manual conversion or honestly it might not be hard to write a tool to do it.)

**Comment by happysalada** [comment]
I don't have a problem with writing it as a md format.
I didn't know there was a testdata directory, considering visibility is limited, it seems better to have it as documentation.
I'll rewrite it and add the missing parts.
Let me know if you feel there are other things that should go in there.

**Comment by andychu** [comment]
OK, I guess `.md` is OK but there is the problem that the code snippets have to be tested.  I think that the tour should quickly go over everything that's idiomatic:

- command language
  - simple commands
    - builtins
    - external commands
  - pipelines
  - control flow
    - if
    - case
    - for
    - while
  - procs
  - variable declaration and mutation
- word language
  - command sub
  - expression sub
  - inline function calls like `@split(x)` and `$join()`
- expression language
  - this is mostly Python
  - eggex


It can have a lot of links to other docs.  It's possible that this doc could get really long so we should find ways to keep it short and sweet.

We can leave out:

- exotic stuff like process sub
- rarely used shell stuff like `until`
- legacy shell stuff: `[[`, `$(( ))`, etc.

**Comment by happysalada** [comment]
I moved things into tour.oil
Thank you for providing the outline.
I tried to include it with some indentation with several ##. This is not standard. I was thinking otherwise it could be included in separate functions ?

The only change I did to your outline was to bump up the variables section.

It's not complete, I can continue once we agree on the format.

**Comment by andychu** [comment]
Sorry for the delay.  I think the  "Learn X in Y Minutes" style is pretty readable.  I was just suggesting a list of topics to cover -- and I think Learn Bash in Y minutes covers all of those.

If you aren't sure about a topic then you can just leave it out and I'll fill it in.  I think it's useful to make something that's readable to you or your friend, using the Learn X in Y style.

----

I added a `hello.oil` and a function to run it:

https://github.com/oilshell/oil/commit/1bdad7c849456d33cf6ba8711a657983b84b1de2

So we can run this with

    oil_lang/run.sh all-passing

**Comment by andychu** [comment]
I'm feeling the need for the "Tour of Oil", e.g. see this comment responding to someone who said Oil's control flow was cryptic (?)

https://lobste.rs/s/d9xics/bourne_shell_bash_aren_t_right_languages#c_ygbqib

Maybe as a first pass you can just add the things that confused you in your initial feedback on issue #934?

That is just have a section on if statements.  And then we can fill it in gradually.

I have also made a few changes recently -- actually based on your feedback.  In `doc/strings.md` there is a bunch of new content and a quick reference:

https://github.com/oilshell/oil/blob/master/doc/strings.md#quick-reference

I think that is good material for the tour of Oil.  But I should probably add it because not everything works yet! :-/

**Comment by happysalada** [comment]
I've added everything I used so far.
Still missing are for, while, blocks, fork.
I think it should be a pretty good start though.

Here are some comments
- I couldn't make the `echo -n $my_string` fail. My understanding of write is that it's supposed to act as a better echo. but I couldn't find use cases for it. I put what I knew about it, but I feel the case for `write` is weak as it is. I would be interested in having more examples
- There are currently 3 ways to use strings r' c' $'. I feel it would be good to recommend one, or differentiate properly with use cases for each. As I understand it $' is for using with newline strings, c' is null byte terminated strings. So as I understand the default recommendation should be $' ?
- The implicit run marked here does not work https://www.oilshell.org/release/latest/doc/idioms.html#if-and-errexit

Let me know if anything.

**Comment by andychu** [comment]
1.  The issue with echo is that `echo $x` does NOT print an arbitrary string, which is a useful operation.  If x happens to be `-n` or `-e`, then it will be treated as a flag, and not printed.  There's no way to fix this in echo; it doesn't respect `--`.  `printf '%s' "$x"` is the POSIX way to do it.  But Oil provides `write -- $x` for simplicity.
2. Yes!   I just  got rid of `c''`.  Brainstorming on the Zulip thread: https://oilshell.zulipchat.com/#narrow/stream/202008-oil-documentation/topic/String.20Brainstorming.20.28quoting.20issue.20.28strict_errexit.20error.2E.2E.2E
3. What doesn't work?  Can you provide an repro of what you expected to work and what didn't?

**Comment by andychu** [comment]
Good news is that the shell script actually catches bugs here, i.e. it caught the fact that we no longer accept `c''`, and a few other things:

https://github.com/oilshell/oil/commit/aae6eec4df42c1f9a761c62cad9f4963ac0710e1

So we want to sketch it first here to make sure it works, and then convert it to a proper doc

**Comment by happysalada** [comment]
Feel free to re-order as you like, no worries from my side!

in this document it says that run is implicit https://www.oilshell.org/release/latest/doc/idioms.html#if-and-errexit
However if you try to put a proc in an if condition without run, it will throw an error
```
./test.sh:6: fatal: Can't run a proc while errexit is disabled. Use 'run' or wrap it in a process with $0 myproc
```
If you want to test it, replace `if run err_today` with `if err_today` in tour.oil

**Pull request merged**
