### PR TITLE
[spec/redirect] Add a test for bash's handling of >&file

### PR DESCRIPTION
**Pull request by watk**
Add a spec test for this bash only behaviour. From the man page:
```
There are two formats for redirecting standard output and standard error:
    &>word
and
    >&word
```

Should osh be matching this behaviour do you think? It's in ubuntu's default bashrc (which is how I came across this):
```
λ grep '>&' /etc/skel/.bashrc
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
```

### CODE REVIEW

**Comment by andychu** [comment]
The philosophical issue is basically that we have to balance old and new ... i.e. is the effort/reward of implementing bash more going to grow the project?  Or should we concentrate more on the Oil language?   It's a difficult balance

Maybe this is a small change and it's worth it (seems like it should be, although I would want to hide it behind `shopt --set strict_redirect` in Oil/YSH)

I'm on the fence here, but I know we have more  compatibility stuff to do, like #1450 


I can share my `bashrc` and `oshrc` right now, and I think that's a very useful milestone ... but yeah there will probably be a lot of people that run into this.  

One thing to try is to simply change it to `&>` and see what the next problem in `bashrc` is.  Probably `bind` ?

----

But we should have this spec test EITHER way, to document the difference.

**Comment by andychu** [comment]
Oh BTW this is bug #746

**Comment by watk** [comment]
> I was wondering why this test didn't fail though!
Oops, I completely forgot to mention I was running with `--rm-tmp`! I was planning to suggest making this the default and having a flag to `keep-tmp`. But whatever you prefer.


Yep, agreed on all those thoughts. I understand the tension and reluctance to implement stuff like this. I figured that since osh is being described as "bash compatible", that you might want to make this work. 

But if you want to invert this spec test and call bash behaviour a BUG lmk.

**Comment by watk** [comment]
Given that it's low priority, we can just add this spec test for documentation and decide later on whether to implement.

**Comment by andychu** [comment]
Thanks, merged!

Wow good point about `--rm-tmp` ... I will remove that flag and make it the default

It might expose some other bugs

Thanks!

**Pull request merged**
