### PR TITLE
Begin implementing $RANDOM

### PR DESCRIPTION
**Pull request by sethwoodworth**
As requested in #146, I tried my hand at implementing $RANDOM.  Tonight I was able to figure out the asdl generator configuration, where the lexer connects regexes to the Id kinds, the implementation of special cases in `_EvalWordPart` and how to use `pdb` and `util.log` functions to interact with `ovm`.
Clearly, this will need a lot of work.  This still needs, at a minimum:
+ to return a 32b random integer
+ allow setting the variable to seed the psudo-random number generator
+ a better name for the `VSub` kind than `DollarSpecialName`
+ a `C` regex that captures `RANDOM` and `SECONDS` 
+ implement bracket expansion in addition to `DollarName` expansion
+ tests and specs
But I thought it would be worthwhile to start the PR to begin getting feedback.

A few questions that I still have:
+ Am I returning the correct type by using `value.Str`?
For the `_EvalWordPart` function, would you be open to a dict of cases where the keys are `part.tag`?
```
part_tag_actions = {
    word_part_e.LiteralPart: lambda part, part_vals, quoted:  part_vals.append(part_value.String(part.token.val, not quoted),
    word_part_e.EscapedLiteralPart: None,
    word_part_e.SingleQuotedPart: None,
    word_part_e.DoubleQuotedPart: None,
    word_part_e.CommandSubPart: None,
}
value_function = part_tag_actions[part.tag](part, part_vals, quoted)
```
Alternately, 
```

def eval_word_part_LiteralPart(part, part_vals, quoted):
    part_vals.append(part_value.String(part.token.val, not quoted)
part_tag_actions {
    word_part_e.LiteralPart: eval_word_part_LiteralPart,
}
word_part_e.LiteralPart(part, part_vals, quoted)
```
rather than:
```
if part.tag == word_part_e.ArrayLiteralPart:
...
elif part.tag == word_part_e.LiteralPart:
...
elif part.tag == word_part_e.EscapedLiteralPart:
...
elif part.tag == word_part_e.SingleQuotedPart:
...
elif part.tag == word_part_e.DoubleQuotedPart:
...
elif part.tag == word_part_e.CommandSubPart:
...
```
I realize you're likely doing speed optimization here that I am not immediately understanding, and that a function call is costly. But if you're amenable to the proposal at all, I would be happy to send you a PR with a full example that we could discuss.

Thanks again for this wonderful project.  I look forward to using and contributing to `ovm` and `oil`.

### CODE REVIEW

**Comment by andychu** [comment]
Thanks for looking at this!

- Yes, numbers should be `value.Str()`, because shell doesn't really have a number type.  I hope to add a proper number type in the Oil language (still far in the future).
- Please just use the if/elif style for now.  The code is definitely too slow, but a dict won't speed it up enough.  I'm working right now on a translation to C++, and if/elif is better for that.  (Even though I've been using Python for 15+ years, this project is the first one where I've *really* wanted a switch statement!)
- I don't think you should use the lexer to recognize `$RANDOM`.  I thought about this, because it is indeed faster, but the problem is statements like this:

    echo $RANDOM ${RANDOM} ${RANDOM/42/-}

Instead there is yet another if/elif chain in `GetVar()` in `osh/state.py`.  This is not ideal, but I think it makes sense to focus first on the functionality, and then change that style later if necessary.

Just curious: do any shells besides bash implement $RANDOM?  I recall a blog post about random in shell ... let me see if I can dig it up.

**Comment by andychu** [comment]
Oh yeah, this is the post I remember.

https://nullprogram.com/blog/2018/12/25/

Honestly I felt it was overkill / overthinking it.  My guess it that $RANDOM can just use libc `rand()` and `srand()`, so we don't have to bother writing and maintaining our own random number generator.  We can "punt" it to libc.

If a user wants good randomness, they should consult the **kernel** via /dev/{random,urandom} or Linux's new `getrandom()`.

I don't think any shells will give secure randomness, and I don't think any shell scripts should rely on secure randomness!  It is sort of a low quality best-effort thing.

**Comment by sethwoodworth** [comment]
If you'd prefer, I'll implement SECONDS instead. This is more an exercise in understanding the codebase than a feature I currently need.

**Comment by andychu** [comment]
Well I think it's important to prioritize by features that real shell programs use.  There's a very long tail of bash features that we could get caught up in.  I won't be surprised if people use RANDOM or SECONDS, but I'd like to know where!

Running programs in the wild usually reveals bugs pretty quickly.  I put some suggestions here:

https://github.com/oilshell/oil/wiki/Shell-Programs-That-Run-Under-OSH

Although it is getting to the point where many common scripts run.

What happens when you try to `source ~/.bashrc` in OSH?  (Maybe you hit https://github.com/oilshell/oil/issues/236 like I do.)

My main goal right now is for people to use OSH.  I think that is mostly blocked on interactive features, but I'm sure there are some language/builtin issues left as well.

**Comment by andychu** [comment]
In other words I guess I'm curious what is preventing people from switching to OSH right now.  My guess is:

1) Some interactive bugs
2) OSH is slower but doesn't have that many more features.  Is there a killer feature that would make you switch?  (I can think of a few, but I'm curious what other people say.  Some of them will also take a long time to implement unfortunately.)

**Comment by jyn514** [comment]
This is what I get when I `source ~/.bashrc`:

```
osh$ . /home/joshua/.bashrc 
osh 'shopt' usage error: Invalid option 'checkwinsize'
osh 'shopt' usage error: Invalid option 'globstar'
osh 'shopt' usage error: Invalid option 'checkhash'
Line 330 of '/usr/share/bash-completion/bash_completion'
      local "$2" "$3" "$4" && _upvars -a${#words[@]} $2 "${words[@]}" \
            ^
Variable names must be unquoted constants
```

I think bash_completion is a known issue, but the `shopt`s might be new. From the manpage:

```
              checkhash
                      If  set,  bash  checks that a command found in the hash table exists
                      before trying to execute it.  If a hashed command no longer  exists,
                      a normal path search is performed.
...
              checkwinsize
                      If  set, bash checks the window size after each command and, if nec‐
                      essary, updates the values of LINES and COLUMNS.
...
              globstar
                      If  set,  the  pattern  ** used in a pathname expansion context will
                      match all files and zero or more directories and subdirectories.  If
                      the  pattern is followed by a /, only directories and subdirectories
                      match.

```

**Comment by sethwoodworth** [comment]
In that case, I'll close this PR and look into shopts

**Comment by andychu** [comment]
@sethwoodworth Thanks, I've already stubbed out a bunch of 'shopt' as no-ops, and that might be OK here.

- checkhash: doesn't apply to OSH, maybe it's OK to stub out.
- checkwinsize: I think this could be useful, but I wonder who uses it?
- globstar: This is #232, probably shouldn't be stubbed out because that would be misleading.  I expect people will want this, but it's an open question on how to do it.  We don't implement our own glob parser, so I'm not sure how to implement `**`.  Some research in this area would be valuable.

Honestly I have a hard time understanding how this feature even works... I put some experiments in `demo/globstar.sh` if anyone wants to play with them.

**Comment by andychu** [comment]
And yes @jyn514 the "unquoted constants" error is because we don't have dynamic assignment, https://github.com/oilshell/oil/issues/236 .  That is not hard, but it's probably going to be a large-ish change.

**Comment by jyn514** [comment]
I think implementing `**` when it's the only part of a path fragment is fine, I don't know how much it's used besides that. So we stay consistent with bash's treatment of `$root/**` and `$root/**/` but ignore all the other cases.

BTW, `$root/**.py` doesn't match *anything*.

**Comment by Aversiste** [comment]
@andychu I use RANDOM on my [rr](https://github.com/Aversiste/rr) project but only if no better tool is available for obtaining random numbers. It is neither safe to use nor serious.

**Comment by Aversiste** [comment]
I spotted one legitimate usage of RANDOM: ensuring all cron jobs are executed daily but not at the exact same time. An example of such use can be seen in [acme-client(1)](https://man.openbsd.org/acme-client#EXAMPLES) man page.

**Pull request closed without merging**
