### PR TITLE
[cpp] posix::_exit() now calls _exit(), not exit() (#1233)

### PR DESCRIPTION
**Pull request by watk**
Calls in python to posix._exit() were being translated into calls to
exit(), which has different semantics. Now it calls _exit() as expected.

Testing:
```bash
> cat >/tmp/f.sh <<'EOF'
echo start
$(:)
echo end
EOF

# before this change
> _bin/cxx-dbg/osh_eval /tmp/f.sh
start
end
end

# with this change
> _bin/cxx-dbg/osh_eval /tmp/f.sh
start
end
```

@andychu Sorry if this is mentioned somewhere and I missed it. Will the CI automatically flag any regressions caused by a change like this? I'm not sure if I should be running something locally to verify or not

### CODE REVIEW

**Comment by andychu** [comment]
Thanks for doing this!  

I'm not sure why the CI isn't running for your PRs and they are for Jesse's

I added you as a collaborator to the project and maybe that will fix it

Let me look at his PRs first and then circle back... I do want to see what the spec tests results are!

**Comment by andychu** [comment]
Ah OK I pulled your PR and then pushed to a branch, and now it's running the CI.

https://github.com/oilshell/oil/actions/runs/2708946912

Hopefully next time it will run automatically with your PRs, if you're a contributor

Let's see what happens!

**Comment by watk** [comment]
Oh sweet thanks! 

I should add a spec test that fails before this change

**Comment by andychu** [comment]
Everything passes with this change which is great:

http://travis-ci.oilshell.org/github-jobs/

I believe it's a good change just based on your explanation (and the crazy StackOverflow thread!!)

---

But yeah nothing changed here?

http://travis-ci.oilshell.org/github-jobs/2022-07-21__02-48-42.wwz/_tmp/spec/cpp/osh-summary.html

But maybe it would when we get rid of the

```
  setvbuf(stdout, 0, _IONBF, 0);
  setvbuf(stderr, 0, _IONBF, 0);
```

in the `main()` of  `osh_eval` ?

https://github.com/oilshell/oil/blob/master/build/translate.sh#L60

----

If you can think of a failing case that would be nice (and could catch future errors), but it's not essential to merge this

**Comment by andychu** [comment]
Oh duh you could just copy this test case in to `spec/bugs.test.sh` 

```
echo start
$(:)
echo end
```

which you run as usual with

```
test/spec.sh bugs
test/spec-cpp.sh run-with-osh-eval bugs
```

(sorry doing too many things at once)

**Comment by watk** [comment]
> Oh duh you could just copy this test case in to spec/bugs.test.sh

Oh perfect, thanks! Done in a new commit, and verified it fails before and passes after.

**Comment by watk** [comment]
> I'm not sure why the CI isn't running for your PRs and they are for Jesse's

Could it be because I'm making changes in a fork but Jesse is pushing to the oil repo?

**Comment by andychu** [comment]
Thank you!

I think I might need to change our YAML config: https://stackoverflow.com/questions/64802322/running-github-actions-on-the-code-in-a-pull-request-from-a-fork

**Pull request merged**
