### PR TITLE
Give a more helpful error if all `help` is missing

### PR DESCRIPTION
**Pull request by jyn514**
This is failing because `os_path` doesn't implement the `exists` function:

```
  File "/home/joshua/src/oil/osh/builtin_misc.py", line 598, in Run
    if not self.loader.Exists('_devbuild/help'):
  File "/home/joshua/src/oil/core/pyutil.py", line 91, in Exists
    return os_path.exists(os_path.join(self.root_dir, rel_path))
AttributeError: 'module' object has no attribute 'exists'
```

I'm not sure how to implement it in pure python, I thought I'd reach out for help.

Addresses #623.

### CODE REVIEW

**Comment by andychu** [comment]
Oh sorry this PR got buried below the bugs in my e-mail ...

We do have `pylib/path_stat.py exists()`, although that wouldn't work when it's in a zip file.  Let me think about what a good strategy is here

**Comment by andychu** [comment]
Oh one possibility is just do hide it behind 

```
if mylib.PYTHON:
  import path_stat
  if path_stat.exists('_devbuild/help'):
    ...
```

That won't get translated to C++.  I think it's OK to add this one-off, as opposed to change the loader interface for something that only happens in dev builds.

**Comment by jyn514** [comment]
> We do have pylib/path_stat.py exists()

Ooh that worked, thanks!

>  I think it's OK to add this one-off, as opposed to change the loader interface for something that only happens in dev builds.

`loader.Exists()` seems like it would be useful in other contexts. I don't have one in mind off the top of my head but adding to the interface seems better than adding hacks.

**Comment by andychu** [comment]
But there is no implementation of Exists() for _ZipResourceLoader.  _FileResourceLoader and _ZipResourceLoader are polymorphic and should both implement _ResourceLoader.  

I'm pretty sure this will cause some MyPy type errors.  It may say something to the effect of _ResourceLoader doesn't have a method `Exists()`.

The way I check is `types/oil-slice.sh travis` (and I won't be surprised if there is a roadbump in running that that we need to fix, feel free to file a bug)

----

I think one other possibility is 

```
loader.HelpExists()
```

_ZipResourceLoader should always return True.  And then _FileResourceLoader returns if _devbuild/help exists.

That is probably a cleaner way to do it that obeys the "rules" of inheritance ...

It should still be hidden behind `if mylib.PYTHON`

**Comment by andychu** [comment]
Hm actually it appears type checking passed

https://travis-ci.org/github/oilshell/oil/jobs/711840034

but I'm not sure why, as `self.loader` is of type `_ResourceLoader` so  the base class has to have the method

And `builtin_misc.py` should be type checked

**Comment by andychu** [comment]
(Back from vacation)

I cloned this PR and I saw the type error I expected.  (I'm not sure why Travis didn't flag it -- something to look into later.)

```
andy@lisa ~/git/oilshell/oil2 (pr/794)$ types/oil-slice.sh travis

osh/builtin_misc.py:598: error: "_ResourceLoader" has no attribute "Exists"
Found 1 error in 1 file (checked 72 source files)

FAIL
```

How about the `HelpExists()` change I suggested?  I think that is actually the most natural interface for what we're trying to do.

**Comment by jyn514** [comment]
I am not planning to follow up on this.

**Pull request closed without merging**
