### PR TITLE
Nix development environment

### PR DESCRIPTION
**Pull request by FRidh**
This commit introduces a Nix expression for Oil. It includes test
dependencies needed for running the Travis scripts.

See https://github.com/oilshell/oil/pull/509 for discussion.

### CODE REVIEW

**Comment by andychu** [comment]
In case you didn't see, I had a problem using Nix with temp dirs starting with `_`, described here:

https://github.com/oilshell/oil/pull/509#issuecomment-544370143

Do you know how to exclude those dirs?

**Comment by FRidh** [comment]
@andychu in case you want to `nix-build`, you point in your recipe to the source using the `src` attribute. You could have e.g. `src = builtins.fetchGit ./.;` in which case it will only consider files that are version-controlled or staged. That should solve your issue. In this PR I switched to just a `shell.nix` as you seem to wanted that.

**Comment by andychu** [comment]
Hm not sure I understand.  Can you add something to the README.md about how to use this?

Ideally it would be like:

1. Install nix
2. Run nix-shell
3. build/dev.sh minimal
4. Run bin/osh

Does that work now?

Also it looks like you did a broad search and replace that will break a bunch of things.  Please do the minimal to run `build/dev.sh minimal`, and then the rest of it can be changed later once we have confidence that this works and is desirable.

**Comment by FRidh** [comment]
Closing because #599 got merged

**Pull request closed without merging**
