### PR TITLE
Fix invalid writes in Str::split

### PR DESCRIPTION
**Pull request by jjbandit**
https://github.com/oilshell/oil/pull/1234

Original PR here ^

Opening a new one because it's easier than taking all the spurious changes out of that one.

### CODE REVIEW

**Comment by jjbandit** [comment]
@andychu Ready to merge

**Comment by jjbandit** [comment]
@andychu 

Looks like the build is failing on this ..?
```
status	elapsed	task	script	action	result_html
status=128 max_status=128
128	0.017857	mycpp-git	mycpp/deps.sh	git-clone	-
```

Not exactly sure if that's a problem or just flaky network?

**Review by andychu — COMMENTED** [review]
Great thank you! 

This will unblock the coverage for my_runtime_test

And then I'm wondering if `if (length)` has branch coverage for true and false?  But now we can see, I *think*

**Comment by andychu** [comment]
Oh the funny thing is that the CI is failure is caused by the Docker containers being out of sync with what's in the repo.

i.e. Docker containers built at HEAD will work, but this branch is slightly behind HEAD.

So yeah this one slight flaw of Docker repo model, discussed in `#containers` on Zulip

**Pull request merged**
