### PR TITLE
Turn off buffered IO

### PR DESCRIPTION
**Pull request by jjbandit**
During my marathon debug session yesterday I noticed turning off buffered IO fixes a large number of test cases.

I vote we just bite the perf bullet and turn buffered IO off, make the shell correct, then make it fast.

The 'make it fast' part probably involves rewriting all the IO code to use our own buffering anyways.

### CODE REVIEW

**Comment by jjbandit** [comment]
Closes #1188

**Comment by andychu** [comment]
Ah interesting I didn't know about this function ... I think it makes sense to just get past these failures, and yeah I think we will want to do it a slightly different way later.

The issue is that most shells use POSIX I/O like read() and write(), and not C/C++ I/O like fread/fwrite, which are buffered.  The shell predates libc :)  So our bindings are technically a little wrong, but I want/need Oil to have a little more polymorphism, so that's why they are like that.

Please add a comment about why those functions are there.  Does it have to be in Environ ??  Not at startup?

And please file a bug about changing it to read()/write() later.

Then I will merge.  (note I'll be out for most of the day but back online tonight!)

Thanks this is great!

**Comment by jjbandit** [comment]
> The issue is that most shells use POSIX I/O like read() and write(), and not C/C++ I/O like fread/fwrite, which are buffered. The shell predates libc :) So our bindings are technically a little wrong, but I want/need Oil to have a little more polymorphism, so that's why they are like that.
>

Yeah I assume once we're doing performance if IO becomes a problem we'd want to do our own buffering and use `write` directly.

> Please add a comment about why those functions are there. Does it have to be in Environ ?? Not at startup?
>
Yeah actually I'd prefer to do them at startup .. this is just the first hand-written C++ I could find to put them in.  Is there already an initialize function somewhere?

> And please file a bug about changing it to read()/write() later.
> 

#1201

> Then I will merge. (note I'll be out for most of the day but back online tonight!)
> 
> Thanks this is great!

:ok_hand:

**Comment by andychu** [comment]
Ah yes, please try putting it in the `cpp-skeleton` in `build/translate.sh`.

**Comment by jjbandit** [comment]
> Ah yes, please try putting it in the `cpp-skeleton` in `build/translate.sh`.

Updated

**Pull request merged**
