### PR TITLE
[cpp] Remove obsolete maskbit_v()

### PR DESCRIPTION
**Pull request by watk**
Since object headers are no longer embedded in objects maskbit_v() is the same as maskbit(), so remove it.

### CODE REVIEW

**Comment by watk** [comment]
Note: I'll change the target branch of this PR to soil-staging after dev-watk-1 is merged

**Comment by andychu** [comment]
Hm I tried changing it to soil-staging, but there were conflicts?

**Comment by watk** [comment]
Oh thanks, yeah I have no idea how to make a dependent PR workflow work (with squash merges I guess?). 

Usually I guess after the base branch goes in, I'd rebase picking only the new commits on this branch, and force push.

But this time I tried `git merge origin/soil-staging -X ours` to not have to force push :shrug: I'll have to research if there's a better workflow

**Comment by andychu** [comment]
Great thank you!

Yeah I haven't used that workflow on Github

Usually when Github reaches it limitations I drop back to the CLI

**Pull request merged**
