### PR TITLE
Use system mypy if it is the only option

### LINKED ISSUE #1041: Typechecking script should use system version mypy if it is the only instance
Noticed that the scripts assume mypy is installed via pip.

Simple fix: #1042 

Broader question: how should one treat search paths for dependencies in general?

### PR DESCRIPTION
**Pull request by emdash**
Created to fix #1041

### CODE REVIEW

**Comment by andychu** [comment]
Hm github is showing me all the diffs from your other change ... haven't seen that before

**Comment by andychu** [comment]
Though I kinda think you want to use the same version of MyPy as the continuous build?  Why not install it from pip3?

**Comment by emdash** [comment]
> Though I kinda think you want to use the same version of MyPy as the continuous build? Why not install it from pip3?

Mainly, forward thinking:
- containerized builds which target a specific base image
- downstream maintainers who want to run unit tests against their official packages
- "meta distros": nix, buildroot, yocto: these have their own requirements.
- some future user, who does the equivalent `apt-get build-dep osh`

Other considerations:
- At some point, PyPI might diverge from the version of mypy you choose to adopt.
- At some point, PyPI might become defunct
 - recent drama with `npm`
 - `pip search` is still broken

Not really trying to ignite a debate though.

**Comment by emdash** [comment]
> Hm github is showing me all the diffs from your other change ... haven't seen that before

This is because github is bad at guessing the correct base branch. I think I can fix this.

**Comment by andychu** [comment]
OK well how about just making a MYPY or MYPY_BIN variable you can  override?

Or if it's not in the $PATH, then fall back to the pip location.  I think the problem is that pip2 doesn't put it in $PATH on my machine, so that's why it's like that.

Also we should have a better name than `types/oil-slice.sh travis` ... I can do that part.

**Comment by emdash** [comment]
> OK well how about just making a MYPY or MYPY_BIN variable you can override?
> 
> Or if it's not in the $PATH, then fall back to the pip location. I think the problem is that pip2 doesn't put it in $PATH on my machine, so that's why it's like that.
> 
> Also we should have a better name than `types/oil-slice.sh travis` ... I can do that part.

I was thinking the usual colon-separated list of search paths would make sense, just not sure what the shell idiom is for that. My guess is that you want some general mechanism to use for all build dependencies like this, I'm just not sure what it is.

**Comment by andychu** [comment]
Actually we do have build/dev-shell.sh, which modifies $PATH, and is sourced by several of our scripts

Yeah let me take a stab at this.  I think I can make it work for both cases, and make it more consistent

**Comment by andychu** [comment]
Actually I think this is OK, except just make the third option plain `mypy`, not /usr/bin/mypy.

That will find the one installed by your package manager

**Comment by emdash** [comment]
Fair.

**Comment by emdash** [comment]
Updated, moving on.

**Pull request merged**
