### PR TITLE
add breaking test for #1767

### PR DESCRIPTION
**Pull request by AtomsForPeace**
How does this look? 
I added an expected failure but the osh case doesn't fail.
I've just tried the check the status codes of the commands. 

I assume this is because the current failure also returns a status code of 2. 
Is there another way I could test this then? Maybe the error text that's returned?
Is there a way to see a diff in the expected vs actual result of one of these tests?

### CODE REVIEW

**Comment by andychu** [comment]
Oh I see this is a difference between OSH and YSH!  I didn't realize that about the bug


```
$ bin/osh -c 'echo (42)'
  echo (42)
       ^
[ -c flag ]:1: 'echo' got unexpected typed args
andy@hoover:~/git/oilshell/oil$ bin/ysh -c 'echo (42)'

```

In that case, I suggest  keeping this test, and then adding another one in one of the  `spec/ysh-*` files

I guess it could go in `spec/ysh-builtins`

**Comment by andychu** [comment]
Oh also I just sent you an invite to work on `oilshell/oil` directly

Sorry there is an issue where we can't run our CI from `AtomsForPeace/oil`, even if I give you permissions.  It's a github actions secrets issue

https://github.com/oilshell/oil/wiki/Contributing

I'll make a note of this on Zulip, we might be able to change the auth on our CI server (?)

**Comment by AtomsForPeace** [comment]
So I'm a bit confused with what the tests are showing.
echo (x) gives me an undefined variable 'x' error as expected so that one's fine
echo (42) returns a blank line in the interactive shell but the test says it returns a status of 2 which I don't understand.

**Comment by AtomsForPeace** [comment]
Closing this in favour of #1804

**Pull request closed without merging**
