### PR TITLE
Jesse/feature/use mmap always

### PR DESCRIPTION
**Pull request by jjbandit**
Pretty straight-forward change which simplified the Heap struct quite a bit.

I was able to remove `GC_NO_HACK` and `GC_PROTECT` by virtue of using `mmap()`.

First, we never need to clear pages because the OS does that when they're faulted in.

Second, we never need to call memprotect() because we jettison the entire mapping every time the collector hits.  We maintain the invariant that the program crashes if anyone tries to access the old zone; munmap makes sure of that.

### CODE REVIEW

**Comment by jjbandit** [comment]
I have no idea why the CI is failing on this @andychu .. I'm getting failures in `mycpp/TEST.sh test-translator` for reasons that are very opaque to me

**Comment by andychu** [comment]
I think this is  a real failure, from the log:

```
[41/192] example-task containers C++ _bin/cxx-opt/mycpp/examples/containers.mycpp _test/tasks/benchmark/containers.opt.task.txt _test/tasks/benchmark/containers.opt.log.txt
FAILED: _test/tasks/benchmark/containers.opt.task.txt _test/tasks/benchmark/containers.opt.log.txt 
```

then go to:

http://travis-ci.oilshell.org/github-jobs/2022-09-01__19-47-09.wwz/_test/tasks/benchmark/containers.opt.log.txt

Let me know if you can't reproduce locally

remember there is the `BENCHMARK=1` environment variable on each of the binaries

https://github.com/oilshell/oil/wiki/Oil-Dev-Cheat-Sheet

**Comment by andychu** [comment]
The general idea looks like it makes sense, I'm not sure why the crash ... I would try running the all the benchmarks and all the tests and see if there is a pattern?

The benchmarks are different than the tests because they tend to allocate more and cause resizing

So that could be the cause of the bug ... it's possible it's exposing a latent bug

**Comment by andychu** [comment]
This one might conflict a little ...

https://github.com/oilshell/oil/pull/1297

It exposes the 200 ms pause problem in debug mode, but it actually didn't cause a problem with tests, since most of them run in opt mode on CI.  (but not locally!   so you may see the delay)

**Comment by andychu** [comment]
OK I think this boils down to needing a better test runner, which I queried about  yesterday:

https://lobste.rs/s/belqch/how_would_you_run_python_c_tests_parallel#c_eq5u6g

The error there but hidden in other errors, let's talk about it on VC

**Pull request closed without merging**
